# https://numtide.github.io/devshell
[devshell]
motd = '''
{bold}{14}🔨 Welcome to the WWW shell! 🔨{reset}
$(type -p menu &>/dev/null && menu)
'''
packages = [
  "go",
  "pulumi"
]

[[commands]]
name = "build"
category = "Code"
help = "Build golang project"
command = "go build"

[[commands]]
name = "deploy-preview"
category = "Infra"
help = "Preview Pulumi changes"
command = "pulumi preview"
