# https://numtide.github.io/devshell
[devshell]
motd = '''
{bold}{14}🔨 Welcome to the WWW shell! 🔨{reset}
$(type -p menu &>/dev/null && menu)
'''
packages = [
  "awscli2",
  "go",
  "html-tidy",
  "nodejs_22",
  "python3",
  "pulumi",
  "pulumiPackages.pulumi-language-go",
  "python3",
  "html-tidy"
]

# Category - CODE

[[commands]]
name = "build-go"
category = "Code"
help = "Build golang project"
command = "go build"

[[commands]]
name = "build"
category = "Code"
help = "Build the entire project"
command = "build-go"

[[commands]]
name = "fmt-go"
category = "Code"
help = "Format golang project"
command = "go fmt"

[[commands]]
name = "fmt-html"
category = "Code"
help = "Format html files"
command = "sh -c 'for f in $(find . -name \"*.html\"); do tidy -m -i -c $f || true; done'" # ignore errors as tidy returns 1 on warnings

[[commands]]
name = "fmt"
category = "Code"
help = "Format entire project"
command = "fmt-go && fmt-html"

# Category - INFRA

[[commands]]
name = "deploy-preview"
category = "Infra"
help = "Preview Pulumi changes"
command = "pulumi stack select prod && pulumi preview"

[[commands]]
name = "deploy"
category = "Infra"
help = "Deploy Pulumi changes"
command = "pulumi stack select prod && pulumi up --yes"

[[commands]]
name = "start-http-server-gardencenter"
category = "Infra"
help = "Start a simple http server and serve the Sramek garden center webpages"
command = "python3 -m http.server 8065 -b localhost --directory ./www/sramek-garden-center/"

[[commands]]
name = "start-http-server-transportation"
category = "Infra"
help = "Start a simple http server and serve the Sramek transportaion webpages"
command = "python3 -m http.server 8066 -b localhost --directory ./www/sramek-transportation/"

