version: '3'

tasks:
  www-transport-up:
    cmds:
      - python3 -m http.server 8066 -b localhost --directory ./www/sramek-transportation/

  www-garden-up:
    cmds:
      - python3 -m http.server 8067 -b localhost --directory ./www/sramek-garden-center/
  
  www-garden-html-fix:
    cmds:
      - for f in $(find ./www/sramek-garden-center/ -name "*.html"); do echo $f && tidy --custom-tags blocklevel -m -i -c $f || true; done

  build-infra:
    dir: './infra/src'
    cmds:
      - go fmt
      - go build

  deploy-infra:
    cmds:
      - pulumi stack select prod && pulumi up