name: "Deploy main branch"
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - name: code_build 
      run: nix develop --command bash -c "build"
    - name: code_fmt
      run: nix develop --command bash -c "fmt"

  # code_fmt:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: cachix/install-nix-action@v22
  #     with:
  #       github_access_token: ${{ secrets.GITHUB_TOKEN }}
  #   - run: |
  #       nix run '.#devShell' -- fmt-go
  #       nix run '.#devShell' -- fmt-html
  #   - uses: EndBug/add-and-commit@v9
  #     with:
  #       add: '.'
  #       author_name: GitHub Actions
  #       author_email: jacfal.tech@protonmail.com
  #       message: "Github Actions: Code fmt"
  # deploy_main:
  #   #if: github.ref == 'refs/heads/main'
  #   needs: [code_fmt]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: cachix/install-nix-action@v22
  #     with:
  #       github_access_token: ${{ secrets.GITHUB_TOKEN }}
  #   - run: |
  #       nix run '.#devShell' -- deploy