name: "Deploy main branch"
on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Parcel build garden center website"
      run: nix develop --command bash -c "npm install ./www/sramek-garden-center/ && npx parcel build www/sramek-garden-center/index.html"
    - name: "Parcel build transportation website"
      run: nix develop --command bash -c "npm install ./www/sramek-transportation/ && npx parcel build www/sramek-transportation/index.html"